# Generated by Django 4.1.6 on 2023-02-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0002_remove_member_books_bookinstance_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location_type',
            field=models.CharField(blank=True, choices=[('h', 'Home'), ('b', 'Business'), ('ps', 'Public Space')], default='e', help_text='Location Type', max_length=2),
        ),
    ]
